# $Id: Makefile,v 1.1 2011-03-24 17:21:42-07 - - $

#
# Article: 856 of ucsc.class.cmps112
# From: Daniel Keller <keller@ucsc.edu>
# Macros should not be replaced until they are used (not when they
# are first seen). E.g. The following makefile should print 'Heller':
#

X       = Orwell
Y       = ${X}
X       = Heller
all:
	echo  ${Y}

