# CS 111 Winter 16
# MakeFile for ASG 2, testing program(s)

all : fork_bomb write_bomb

fork_bomb : 
	cc -o fork_bomb fork_bomb.c  -Wall

write_bomb : 
	cc -o write_bomb write_bomb.c  -Wall

clean :
	rm fork_bomb write_bomb in out
