# Makefile.dep created Sun May 17 18:30:04 PDT 2015
trace.o: trace.cpp trace.h
util.o: util.cpp util.h trace.h util.tcc
main.o: main.cpp listmap.h xless.h xpair.h listmap.tcc trace.h util.h \
 util.tcc
