sample :
	- rm Sample.class
	javac Sample.java
	java -classpath /Users/tim/Google\ Drive/Dropbox/School/CS180/lab4/postgresql-9.4.1208.jar:. Sample

driver :
	- rm StoreApplication.class
	- rm Driver.class
	javac StoreApplication.java
	javac Driver.java
	java -classpath /Users/tim/Google\ Drive/Dropbox/School/CS180/lab4/postgresql-9.4.1208.jar:. Driver

